### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PeyTy** [openhaxe/Destroy-Me-When-Became-Useless#19]
- [ ] Lowering types: char of string is i8, it can be extended to i32/i16/i64/double on demand
- [ ] String creation
- [ ] String concat
- [ ] String ARC retain
- [ ] String ARC free
- [ ] String get char at
- [ ] Object ARC retain
- [ ] Object ARC free
- [ ] Object ARC free with destructor (for Dynamics and objects with destructors)
- [x] Main init expr
- [ ] Static fields expr init
- [ ] Instance fields expr init
- [ ] Send self pointer to instance methods and constructor
- [ ] Build and record instance structure (as a pointer*)
- [ ] Complete type description
- [x] Array[Int] allocate
- [x] Array[Int] read (unsafe)
- [x] Array[Int] write (with length extending)
- [ ] Array[Int] push
- [ ] Array[Int] get length
- [ ] trace with toString call
- [ ] trace String
- [ ] trace multiple arguments with printf
- [ ] nullability and optional args as pointer-to-arg-or-null
- [ ] embed compiled resources
- [ ] cond if
- [ ] cond while
- [ ] booleans op
- [ ] extract local function
- [ ] checkout malloc i64
- [x] checkout keywords
- [ ] make asmjs test alive
- [x] checkout get_ret_temp
- [x] checkout trace override
- [ ] printCall refresh
- [ ] checkout bit ops
- [ ] arifmetic operators type review
- [x] cleanup (old) patterns
- [ ] article about undefined memory behavior
