### ISSUE TITLE
TODO №2

### ISSUE THREAD

**Issue by PeyTy** [openhaxe/Destroy-Me-When-Became-Useless#20]
- [ ] push/pop continue/break labels
- [ ] call new()
- [ ] format code (move vars to up etc)
- [ ] doc code
- [ ] use func attrib
- [x] remove function get_temp
- [ ] special tha
- [ ] disallow js libs
- [ ] disable js libs
- [ ] request nullability disabler & package disallower
- [ ] update compilers
- [ ] some cool cmd screenshots
- [ ] share same libs in compilers
